#pragma once

#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_SWAPCHAIN_IMAGES 8

#define MINIMUM_VULKAN_API_SUPPORTED VK_API_VERSION_1_4

#ifndef USE_VALIDATION
#define USE_VALIDATION 0
#endif

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
